# Generated by Django 4.2.5 on 2023-10-28 08:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_bookmarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='bookmarks',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=16), blank=True, default=list, size=None),
        ),
    ]
