# Generated by Django 4.2.5 on 2023-11-01 01:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_bookmarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='LookUpJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_unique_key', models.UUIDField(unique=True)),
                ('jobid', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=16), blank=True, default=list, size=None)),
            ],
        ),
    ]
