# Generated by Django 4.2.5 on 2023-10-18 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobid', models.CharField(max_length=255, unique=True)),
                ('date_scraped', models.DateField()),
                ('job_title', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('company_location', models.CharField(max_length=255)),
                ('salary', models.CharField(max_length=255)),
                ('job_description', models.TextField()),
                ('url', models.URLField()),
            ],
        ),
    ]
