# Generated by Django 4.2.5 on 2023-10-19 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobscraper', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapeddata',
            name='salary',
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='job_types',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='max_salary',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='min_salary',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='qualifications',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='salary_unit',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='schedule',
            field=models.TextField(default=None, null=True),
        ),
    ]
