# Generated by Django 4.2.5 on 2023-10-19 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobscraper', '0002_remove_scrapeddata_salary_scrapeddata_job_types_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapeddata',
            name='max_salary',
            field=models.DecimalField(decimal_places=1, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='scrapeddata',
            name='min_salary',
            field=models.DecimalField(decimal_places=1, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='scrapeddata',
            name='salary_unit',
            field=models.TextField(default=None, null=True),
        ),
    ]
