# Generated by Django 4.2.5 on 2023-10-19 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobscraper', '0003_alter_scrapeddata_max_salary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapeddata',
            name='qualifications',
        ),
    ]
