# Generated by Django 4.2.5 on 2023-10-19 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobscraper', '0004_remove_scrapeddata_qualifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapeddata',
            name='schedule',
        ),
    ]
