# Generated by Django 4.2.5 on 2023-10-19 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobscraper', '0005_remove_scrapeddata_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapeddata',
            name='max_salary',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='scrapeddata',
            name='min_salary',
            field=models.FloatField(default=None, null=True),
        ),
    ]
