# Generated by Django 4.2.5 on 2023-10-19 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobscraper', '0006_alter_scrapeddata_max_salary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapeddata',
            name='date_scraped',
            field=models.DateField(blank=True, null=True),
        ),
    ]
