# Generated by Django 4.2.5 on 2023-11-03 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobscraper', '0007_alter_scrapeddata_date_scraped'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapeddata',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
